DROP TABLE USERS;

CREATE TABLE USERS(
 USERNAME VARCHAR2(10) PRIMARY KEY,
 PASSWORD VARCHAR2(100),
 NAME VARCHAR2(30),
 ROLE VARCHAR2(12),
 ENABLED BOOLEAN
);
INSERT INTO USERS VALUES('manager', 'test123', '매니저', 'MANAGER', TRUE);
INSERT INTO USERS VALUES('admin', 'test123', '어드민', 'ADMIN', TRUE);
